# Generated by Django 4.2.30 on 2026-06-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
