# Generated by Django 6.0.6 on 2026-06-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='puertos',
            field=models.CharField(default='22,80,443', help_text='Lista de puertos separados por comas', max_length=200),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='host',
            field=models.CharField(help_text='Dirección IP o nombre DNS', max_length=255),
        ),
    ]
